apiVersion: v1
kind: Secret
metadata:
  name: website-2026-secrets
  namespace: website-2026
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: change_me_root_password
  USER_JWT_SECRET: change_me_user_jwt_secret
  ADMIN_JWT_SECRET: change_me_admin_jwt_secret
  MINIO_ACCESS_KEY: admin
  MINIO_SECRET_KEY: password123
